### ISSUE TITLE
satilink-ws-6933 codes with RS6000B

### ISSUE THREAD

**Issue by czorgormez** [rydsfoz/satilink-ws-6933#1]
hi is it possible to you share codes for satilink-ws-6933  with RS6000B ?

**Comment by rydsfoz** [comment]
The problem is that the source code was obtained (in part) by reverse engineering, I don't know if there would be any problem publishing the code because of that. Reverse engineering was used because many of the integrated circuits do not have a datasheet (or are incomplete).
